eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: feign-consumer

server:
  port: 9000

#手动开启feign对断路器的支持,新版本默认关闭了的
feign:
   hystrix:
     enabled: true

#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 5000 #默认时间一秒钟

# 可以指定路由地址
#zuul:
#  routes:
#    provider:
#      path: /api/provider/*
#      serviceId: eureka-provider
#    consumer:
#      path: /api/consumer/*
#      serviceId: feign-consumer